modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/PG85/OpenTerrainGenerator/issues"

[[mods]]
modId="otg"
version="${version}"
displayName="Open Terrain Generator"
displayURL="https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator"
logoFile="OTGlogo.png"
credits="Team OTG, TerrainControl Maintainers"
authors="Team OTG"
description='''
OTG: Generate anything!
'''

[[dependencies.otg]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.otg]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
